import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "dark",
        "antialiased",
        geistSans.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="sm:min-h-full grid grid-cols-1 sm:grid-cols-4 grid-rows-[49px_1fr]">
        <div className="w-full h-fit bg-surface border-b p-4 flex col-span-4 items-center gap-2 font-mono text-xs">
          <div className="flex gap-2">
            <span className="text-accent font-semibold">
              web3-siwe-middleware
            </span>
            <span className="text-muted">/</span>
            <span className="text-muted-foreground">front demo</span>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
